default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: stant_test
  password: stant_test
  pool: 5

development:
  <<: *default
  host: localhost
  database: stant_test_development

test:
  <<: *default
  host: localhost
  database: stant_test_test

production:
  <<: *default
  database: stant_test
